"""
Remediator module - applies tuning recommendations.
"""
import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .ssh_client import SSHClient
from .analyzer import TuningRecommendation


@dataclass
class RemediationAction:
    """Record of a remediation action."""
    timestamp: str
    recommendation: TuningRecommendation
    command_executed: str
    success: bool
    output: str
    rollback_command: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "category": self.recommendation.category,
            "setting": self.recommendation.setting,
            "command": self.command_executed,
            "success": self.success,
            "output": self.output[:500],  # Truncate long output
            "rollback_command": self.rollback_command,
        }


class Remediator:
    """Applies tuning recommendations to the system."""

    def __init__(self, ssh_client: SSHClient, dry_run: bool = False):
        self.ssh = ssh_client
        self.dry_run = dry_run
        self.actions: list[RemediationAction] = []

    def apply_recommendations(
        self,
        recommendations: list[TuningRecommendation],
        categories: Optional[list[str]] = None,
    ) -> list[RemediationAction]:
        """Apply a list of recommendations."""
        results = []

        for rec in recommendations:
            # Filter by category if specified
            if categories and rec.category not in categories:
                continue

            action = self.apply_single(rec)
            results.append(action)
            self.actions.append(action)

        return results

    def apply_single(self, rec: TuningRecommendation) -> RemediationAction:
        """Apply a single recommendation."""
        timestamp = datetime.utcnow().isoformat()

        if self.dry_run:
            return RemediationAction(
                timestamp=timestamp,
                recommendation=rec,
                command_executed=rec.command,
                success=True,
                output="[DRY RUN] Command not executed",
                rollback_command=self._get_rollback_command(rec),
            )

        # Execute the command
        result = self.ssh.run(rec.command, timeout=60)

        # Handle nginx-specific post-actions
        if rec.category == "nginx" and result.success:
            # Test and reload nginx
            test_result = self.ssh.run("nginx -t")
            if test_result.success:
                self.ssh.run("nginx -s reload")

        # Handle kernel params
        if rec.category == "kernel" and result.success:
            # Apply sysctl immediately
            if "sysctl" not in rec.command:
                self.ssh.run("sysctl --system")

        return RemediationAction(
            timestamp=timestamp,
            recommendation=rec,
            command_executed=rec.command,
            success=result.success,
            output=result.output,
            rollback_command=self._get_rollback_command(rec),
        )

    def _get_rollback_command(self, rec: TuningRecommendation) -> Optional[str]:
        """Generate rollback command for a recommendation."""
        if rec.category == "nginx":
            return "cp /etc/nginx/nginx.conf.backup /etc/nginx/nginx.conf && nginx -s reload"
        elif rec.category == "kernel":
            if "sysctl" in rec.command:
                return f"sysctl -w {rec.setting}={rec.current_value}"
        elif rec.category == "disk":
            if "scheduler" in rec.setting:
                return f"echo mq-deadline > /sys/block/nvme0n1/queue/scheduler"
        return None

    def backup_nginx_config(self) -> bool:
        """Create a backup of nginx config before changes."""
        timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        result = self.ssh.run(
            f"cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup.{timestamp}"
        )
        return result.success

    def verify_nginx_config(self) -> tuple[bool, str]:
        """Verify nginx configuration is valid."""
        result = self.ssh.run("nginx -t 2>&1")
        return result.success, result.output

    def reload_nginx(self) -> tuple[bool, str]:
        """Reload nginx to apply changes."""
        result = self.ssh.run("nginx -s reload")
        return result.success, result.output

    def get_actions_log(self) -> list[dict]:
        """Get log of all remediation actions."""
        return [action.to_dict() for action in self.actions]

    def generate_rollback_script(self) -> str:
        """Generate a script to rollback all changes."""
        lines = ["#!/bin/bash", "# Rollback script generated by AI Performance Agent", ""]

        for action in self.actions:
            if action.success and action.rollback_command:
                lines.append(f"# Rollback: {action.recommendation.setting}")
                lines.append(action.rollback_command)
                lines.append("")

        lines.append("# Reload services")
        lines.append("nginx -t && nginx -s reload")
        lines.append("sysctl --system")

        return "\n".join(lines)
